# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    sudo apt-get install -y \
      bison \
      cmake \
      flex \
      libbz2-dev \
      libreadline-dev \
      maven \
      ninja-build \
      openjdk-8-jdk-headless \
      python-dev \
      python-pip \
      rsync \
      uuid-dev
  displayName: Install packages

- script: |
    ./yb_build.sh --skip-java
  displayName: 'Build code'

