# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    docker run yugabytedb/yb_build_infra_ubuntu1804:v2019-04-26T16_05_29_mbautin bash -c "sudo -u yugabuilder bash -c 'mkdir -p ~/code && cd ~/code && git clone https://github.com/yugabyte/yugabyte-db && yugabyte-db && ./yb_build.sh'"
  displayName: 'Build code'

