# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    docker run --mount type=bind,src=$PWD,target=/mnt/yugabyte-db \
        yugabytedb/yb_build_infra_ubuntu1804:v2019-04-26T19_15_03_mbautin \
        bash -c 'cp -R /mnt/yugabyte-db /home/yugabuilder/yugabyte-db && \
                 chown -R yugabuilder /home/yugabuilder/yugabyte-db && \
                 sudo su - yugabuilder bash -c "mkdir -p ~/code && cd ~/code && \
                                                cp -R /mnt/yugabyte-db . && \
                                                cd yugabyte-db && \
                                                ./yb_build.sh"'
  displayName: 'Build code'

