version: 2
jobs:
  ubuntu1804:
    machine: true
    steps:
      - checkout
      - run: 
          no_output_timeout: 1h
          command: |
            docker run --mount type=bind,src=$PWD,target=/mnt/yugabyte-db \
                --name yb_build_container \
                yugabytedb/yb_build_infra_ubuntu1804:v2019-07-24T14_48_25_mbautin \
                bash -c 'mkdir -p /home/yugabyte-ci/code && \
                         cp -R /mnt/yugabyte-db /home/yugabyte-ci/code && \
                         chown -R yugabyte-ci /home/yugabyte-ci/code && \
                         sudo su - yugabyte-ci bash -c \
                             "export YB_SKIP_INITIAL_SYS_CATALOG_SNAPSHOT=1 && \
                              cd ~/code/yugabyte-db && \
                              ./yb_build.sh release"'
      - deploy:
          name: Publish the build result to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker commit yb_build_container "$DOCKERHUB_USER/yugabytedb_ci_build_ubuntu1804:$CIRCLE_SHA1"
            docker push "$DOCKERHUB_USER/yugabytedb_ci_build_ubuntu1804:$CIRCLE_SHA1"
  centos7:
    machine: true
    steps:
      - checkout
      - run: 
          no_output_timeout: 1h
          command: |
            docker run --mount type=bind,src=$PWD,target=/mnt/yugabyte-db \
                --name yb_build_container \
                yugabytedb/yb_build_infra_centos7:v2019-09-01T06_40_19_mbautin \
                bash -c 'mkdir -p /home/yugabyte-ci/code && \
                         cp -R /mnt/yugabyte-db /home/yugabyte-ci/code && \
                         chown -R yugabyte-ci /home/yugabyte-ci/code && \
                         sudo su - yugabyte-ci bash -c \
                             "export YB_SKIP_INITIAL_SYS_CATALOG_SNAPSHOT=1 && \
                              cd ~/code/yugabyte-db && \
                              ./yb_build.sh release"'
      - deploy:
          name: Publish the build result to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker commit yb_build_container "$DOCKERHUB_USER/yugabytedb_ci_build_centos7:$CIRCLE_SHA1"
            docker push "$DOCKERHUB_USER/yugabytedb_ci_build_centos7:$CIRCLE_SHA1"

workflows:
  # See https://circleci.com/docs/2.0/workflows/
  version: 2
  build_yugabyte_db:
    jobs:
      - ubuntu1804 
      - centos7
