version: 2
jobs:
  ubuntu1804:
    machine: true
    steps:
      - checkout
      - setup_remote_docker
      - script: |
          docker run --mount type=bind,src=$PWD,target=/mnt/yugabyte-db \
              yugabytedb/yb_build_infra_ubuntu1804:v2019-04-27T08_37_04_mikhail \
              bash -c 'mkdir -p /home/yugabuilder/code &&
                       cp -R /mnt/yugabyte-db /home/yugabuilder/code && \
                       chown -R yugabuilder /home/yugabuilder/code && \
                       sudo su - yugabuilder bash -c "cd ~/code/yugabyte-db && ./yb_build.sh --ctest --java-tests'

workflows:
  # See https://circleci.com/docs/2.0/workflows/
  version: 2
  build_yugabyte_db:
    jobs:
      - ubuntu1804 
